{{- define "helmet-gift.secrets" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: {{ .Values.secret.type }}
{{- if .Values.secret.data }}
data: {{- include "common.tplvalues.render" (dict "value" .Values.secret.data "context" $) | nindent 2 }}
{{- end }}
{{- if .Values.secret.stringData }}
stringData: {{- include "common.tplvalues.render" (dict "value" .Values.secret.stringData "context" $) | nindent 2 }}
{{- end }}
{{- end }}
